language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed vietcuong179/udagram-api-feed:v3
  - docker tag udagram-api-user vietcuong179/udagram-api-user:v3
  - docker tag udagram-frontend:local vietcuong179/udagram-frontend:v3
  - docker tag reverseproxy vietcuong179/reverseproxy:v3

after_success:
  - docker logout
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push vietcuong179/udagram-api-feed:v3
  - docker push vietcuong179/udagram-api-user:v3
  - docker push vietcuong179/udagram-frontend:v3
  - docker push vietcuong179/reverseproxy:v3
