apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      run: backend-feed
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
      containers:
      - name: backend-feed
        image: vietcuong179/udagram-api-feed:v10
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_USERNAME
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_HOST
          value: mypostgres.cb98ev2dyawy.us-east-1.rds.amazonaws.com
        - name: POSTGRES_DB
          value: cuongnv
        - name: AWS_BUCKET
          value: cuongnv98
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_PROFILE
          value: default
        - name: JWT_SECRET
          value: testing
        - name: URL
          value: http://localhost:8100
