apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      run: backend-user
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
      containers:
      - name: backend-user
        image: vietcuong179/udagram-api-user:v12
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: udagram-env
          - secretRef:
              name: udagramdb-env
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true
