apiVersion: v1
kind: Service
metadata:
  name: publicreverseproxy
  labels:
    service: reverseproxy
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "8080"
    port: 80
    targetPort: 8080
  selector:
    service: reverseproxy
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: a6f0fafb2ec384aa3a363e2fc4063852-1806770700.us-east-2.elb.amazonaws.com